setono_sylius_climate_partner_admin_channel_climate_fee:
    resource: |
        section: admin
        alias: setono_sylius_climate_partner.channel_climate_fee
        templates: "@SyliusAdmin\\Crud"
        redirect: index
        permission: true
        grid: setono_sylius_climate_partner_admin_channel_climate_fee
        vars:
            all:
                header: setono_sylius_climate_partner.ui.channel_climate_fee_header
                subheader: setono_sylius_climate_partner.ui.channel_climate_fee_subheader
                templates:
                    form: "@SetonoSyliusClimatePartnerPlugin/admin/channel_climate_fee/_form.html.twig"
            create:
                templates:
                    breadcrumb: '@SetonoSyliusClimatePartnerPlugin/admin/channel_climate_fee/create/_breadcrumb.html.twig'
            index:
                templates:
                    breadcrumb: '@SetonoSyliusClimatePartnerPlugin/admin/channel_climate_fee/index/_breadcrumb.html.twig'
            update:
                templates:
                    breadcrumb: '@SetonoSyliusClimatePartnerPlugin/admin/channel_climate_fee/update/_breadcrumb.html.twig'
    type: sylius.resource
