<?php

declare(strict_types=1);

namespace Setono\SyliusClimatePartnerPlugin;

use Setono\SyliusClimatePartnerPlugin\DependencyInjection\Compiler\RegisterClimateOffsetTaxesApplicatorPass;
use Sylius\Bundle\CoreBundle\Application\SyliusPluginTrait;
use Sylius\Bundle\ResourceBundle\AbstractResourceBundle;
use Sylius\Bundle\ResourceBundle\SyliusResourceBundle;
use Symfony\Component\DependencyInjection\ContainerBuilder;

final class SetonoSyliusClimatePartnerPlugin extends AbstractResourceBundle
{
    use SyliusPluginTrait;

    public function getSupportedDrivers(): array
    {
        return [
            SyliusResourceBundle::DRIVER_DOCTRINE_ORM,
        ];
    }

    public function build(ContainerBuilder $container): void
    {
        parent::build($container); // TODO: Change the autogenerated stub

        $container->addCompilerPass(new RegisterClimateOffsetTaxesApplicatorPass());
    }
}
