name: "build"
on:
    push:
        branches:
            - "master"
        paths-ignore:
            - "*.md"
    pull_request:
        paths-ignore:
            - "*.md"
    workflow_dispatch: ~

env:
    APP_ENV: "test"
    DATABASE_URL: "mysql://root:root@127.0.0.1/sylius?serverVersion=5.7"
    PHP_EXTENSIONS: "intl, mbstring"

jobs:
    coding-standards:
        name: "Coding Standards (PHP ${{ matrix.php-version }} | Dependency versions: ${{ matrix.dependencies }})"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - "7.4"

                dependencies:
                    - "highest"

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v2"

            -   name: "Setup PHP, with composer and extensions"
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: "${{ matrix.php-version }}"
                    extensions: "${{ env.PHP_EXTENSIONS }}"
                    coverage: "none"

            -   name: "Install composer dependencies"
                uses: "ramsey/composer-install@v1"
                with:
                    dependency-versions: "${{ matrix.dependencies }}"

            -   name: "Validate composer"
                run: "composer validate --strict"

            -   name: "Check composer normalized"
                run: "composer normalize --dry-run"

            -   name: "Check style"
                run: "composer check-style"

            -   name: "Lint yaml files"
                run: "(cd tests/Application && bin/console lint:yaml ../../src/Resources)"

            -   name: "Lint twig files"
                run: "(cd tests/Application && bin/console lint:twig ../../src/Resources)"

    dependency-analysis:
        name: "Dependency Analysis (PHP ${{ matrix.php-version }} | Dependency versions: ${{ matrix.dependencies }} | Symfony: ${{ matrix.symfony }})"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - "7.4"

                dependencies:
                    - "highest"

                symfony:
                    - "^4.4"
                    - "^5.3"

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v2"

            -   name: "Setup PHP, with composer and extensions"
                uses: "shivammathur/setup-php@v2"
                with:
                    coverage: "none"
                    extensions: "${{ env.PHP_EXTENSIONS }}"
                    php-version: "${{ matrix.php-version }}"
                    tools: "composer-require-checker, composer-unused, flex"

            -   name: "Install composer dependencies"
                uses: "ramsey/composer-install@v1"
                env:
                    SYMFONY_REQUIRE: "${{ matrix.symfony }}"
                with:
                    dependency-versions: "${{ matrix.dependencies }}"

            -   name: "Run maglnet/composer-require-checker"
                run: "composer-require-checker check --config-file=$(pwd)/composer-require-checker.json"

            -   name: "Run composer-unused/composer-unused"
                run: "composer-unused"

    static-code-analysis:
        name: "Static Code Analysis (PHP ${{ matrix.php-version }} | Dependency versions: ${{ matrix.dependencies }} | Symfony: ${{ matrix.symfony }})"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - "7.4"

                dependencies:
                    - "highest"

                symfony:
                    - "^4.4"
                    - "^5.3"

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v2"

            -   name: "Setup PHP, with composer and extensions"
                uses: "shivammathur/setup-php@v2"
                with:
                    coverage: "none"
                    extensions: "${{ env.PHP_EXTENSIONS }}"
                    php-version: "${{ matrix.php-version }}"
                    tools: "flex"

            -   name: "Install composer dependencies"
                uses: "ramsey/composer-install@v1"
                env:
                    SYMFONY_REQUIRE: "${{ matrix.symfony }}"
                with:
                    dependency-versions: "${{ matrix.dependencies }}"

            -   name: "Cache warmup"
                run: "(cd tests/Application && bin/console cache:warmup)"

            -   name: "Static analysis"
                run: "composer analyse"

    unit-tests:
        name: "Unit tests (PHP ${{ matrix.php-version }} | Dependency versions: ${{ matrix.dependencies }} | Symfony: ${{ matrix.symfony }})"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - "7.4"

                dependencies:
                    - "highest"

                symfony:
                    - "^4.4"
                    - "^5.3"

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v2"

            -   name: "Setup PHP, with composer and extensions"
                uses: "shivammathur/setup-php@v2"
                with:
                    coverage: "none"
                    extensions: "${{ env.PHP_EXTENSIONS }}"
                    php-version: "${{ matrix.php-version }}"
                    tools: "flex"

            -   name: "Install composer dependencies"
                uses: "ramsey/composer-install@v1"
                env:
                    SYMFONY_REQUIRE: "${{ matrix.symfony }}"
                with:
                    dependency-versions: "${{ matrix.dependencies }}"

            -   name: "Run phpunit"
                run: "composer phpunit"

    integration-tests:
        name: "Integration tests (PHP ${{ matrix.php-version }} | Dependency versions: ${{ matrix.dependencies }} | Symfony: ${{ matrix.symfony }})"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - "7.4"

                dependencies:
                    - "highest"

                symfony:
                    - "^4.4"
                    - "^5.3"

        steps:
            -   name: "Start MySQL"
                run: "sudo systemctl start mysql.service"

            -   name: "Checkout"
                uses: "actions/checkout@v2"

            -   name: "Setup PHP, with composer and extensions"
                uses: "shivammathur/setup-php@v2"
                with:
                    coverage: "none"
                    extensions: "${{ env.PHP_EXTENSIONS }}"
                    php-version: "${{ matrix.php-version }}"
                    tools: "flex"
            
            -   name: "Setup node"
                uses: "actions/setup-node@v2"
                with:
                    node-version: "14.x"

            -   name: "Install composer dependencies"
                uses: "ramsey/composer-install@v1"
                env:
                    SYMFONY_REQUIRE: "${{ matrix.symfony }}"
                with:
                    dependency-versions: "${{ matrix.dependencies }}"

            -   name: "Lint container"
                # Do not lint on SF4 because we get this error: Invalid definition for service "doctrine.migrations.dependency_factory": argument 2 of "Doctrine\Migrations\DependencyFactory::setDefinition()" accepts "callable", "SyliusLabs\DoctrineMigrationsExtraBundle\Factory\ContainerAwareVersionFactory" passed.
                # Note: We cannot use the if statement here, because of https://github.community/t/matrix-cannot-be-used-in-jobs-level-if/17177/10
                run: 'if [ "${{ matrix.symfony }}" != "^4.4" ]; then (cd tests/Application && bin/console lint:container); fi'

            -   name: "Create database"
                run: "(cd tests/Application && bin/console doctrine:database:create -vvv)"

            -   name: "Create database schema"
                run: "(cd tests/Application && bin/console doctrine:schema:create -vvv)"

            -   name: "Validate Doctrine mapping"
                run: "(cd tests/Application && bin/console doctrine:schema:validate -vvv)"

            -   name: "Get Yarn cache directory"
                id: "yarn-cache"
                run: "echo \"::set-output name=dir::$(yarn cache dir)\""

            -   name: "Cache Yarn"
                uses: "actions/cache@v2"
                with:
                    path: "${{ steps.yarn-cache.outputs.dir }}"
                    key: "yarn-${{ hashFiles('**/package.json **/yarn.lock') }}"
                    restore-keys: "yarn-"

            -   name: "Install JS dependencies"
                run: "(cd tests/Application && yarn install)"

            -   name: "Install assets"
                run: "(cd tests/Application && bin/console assets:install)"

            -   name: "Build assets"
                run: "(cd tests/Application && yarn build)"
            
            -   name: "Run behat"
                run: "vendor/bin/behat --colors --strict -vvv --no-interaction || vendor/bin/behat --colors --strict -vvv --no-interaction --rerun"

            -   name: "Upload Behat logs"
                uses: "actions/upload-artifact@v2"
                if: "failure()"
                with:
                    name: "Behat logs"
                    path: "etc/build/"
                    if-no-files-found: "ignore"

    code-coverage:
        name: "Code Coverage (PHP ${{ matrix.php-version }} | Dependency versions: ${{ matrix.dependencies }})"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - "7.4"

                dependencies:
                    - "highest"

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v2"

            -   name: "Setup PHP, with composer and extensions"
                uses: "shivammathur/setup-php@v2"
                with:
                    coverage: "pcov"
                    extensions: "${{ env.PHP_EXTENSIONS }}"
                    php-version: "${{ matrix.php-version }}"

            -   name: "Set up problem matchers for phpunit/phpunit"
                run: "echo \"::add-matcher::${{ runner.tool_cache }}/phpunit.json\""

            -   name: "Install composer dependencies"
                uses: "ramsey/composer-install@v1"
                with:
                    dependency-versions: "${{ matrix.dependencies }}"

            -   name: "Collect code coverage with pcov and phpunit/phpunit"
                run: "vendor/bin/phpunit --coverage-clover=.build/logs/clover.xml"

            -   name: "Send code coverage report to Codecov.io"
                env:
                    CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
                run: "bash <(curl -s https://codecov.io/bash)"
